/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Conexion.Conexion;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Carlos Estevez Vargas
 */
public class Principal extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Supermercado El Furuto");
        this.setResizable(false);
        this.setLocationRelativeTo(null);

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT id_producto, nombre_producto, cantidad_producto, precio_producto, categoria FROM productos");

            ResultSet rs = pst.executeQuery();

            tabla_productos = new JTable(model);
            jScrollPane1.setViewportView(tabla_productos);

            //Columnas de la tabla
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("Categoría");

            //Llenado de la tabla
            while (rs.next()) {
                Object[] fila = new Object[5];

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla clientes " + e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_productos = new javax.swing.JTable();
        btnActualizarTabla = new javax.swing.JButton();
        panelRegistrarProductos = new javax.swing.JPanel();
        labelNombreProducto = new javax.swing.JLabel();
        labelCantidadProducto = new javax.swing.JLabel();
        labelPrecioProducto = new javax.swing.JLabel();
        labelCategoriaProducto = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        txtPrecioProducto = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnGuardarProducto = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        labelNombreProducto1 = new javax.swing.JLabel();
        labelCantidadProducto1 = new javax.swing.JLabel();
        labelPrecioProducto1 = new javax.swing.JLabel();
        labelCategoriaProducto1 = new javax.swing.JLabel();
        cmbActualizarCategoria = new javax.swing.JComboBox<>();
        txtActualizarPrecioProducto = new javax.swing.JTextField();
        txtActualizarCantidadProducto = new javax.swing.JTextField();
        txtActualizarNombreProducto = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnActualizarPorID1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtIDProducto = new javax.swing.JTextField();
        btnEliminarProductos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        tabla_productos.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tabla_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Precio", "Categoría"
            }
        ));
        jScrollPane1.setViewportView(tabla_productos);

        btnActualizarTabla.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnActualizarTabla.setText("Actualizar tabla");
        btnActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(btnActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar", jPanel2);

        labelNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombreProducto.setText("Nombre");

        labelCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCantidadProducto.setText("Cantidad");

        labelPrecioProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPrecioProducto.setText("Precio");

        labelCategoriaProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCategoriaProducto.setText("Categoría");

        txtNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPrecioProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aseo", "Víveres" }));

        btnGuardarProducto.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnGuardarProducto.setText("Guardar");
        btnGuardarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProductoActionPerformed(evt);
            }
        });

        btnSalir1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegistrarProductosLayout = new javax.swing.GroupLayout(panelRegistrarProductos);
        panelRegistrarProductos.setLayout(panelRegistrarProductosLayout);
        panelRegistrarProductosLayout.setHorizontalGroup(
            panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarProductosLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarProductosLayout.createSequentialGroup()
                        .addComponent(labelCategoriaProducto)
                        .addGap(97, 97, 97)
                        .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarProductosLayout.createSequentialGroup()
                        .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreProducto)
                            .addComponent(labelCantidadProducto)
                            .addComponent(labelPrecioProducto))
                        .addGap(73, 73, 73)
                        .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreProducto)
                            .addComponent(txtCantidadProducto)
                            .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGuardarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(66, 66, 66))
        );
        panelRegistrarProductosLayout.setVerticalGroup(
            panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarProductosLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombreProducto)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCantidadProducto)
                    .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarProducto))
                .addGap(13, 13, 13)
                .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioProducto)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir1))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoriaProducto)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registrar", panelRegistrarProductos);

        labelNombreProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelNombreProducto1.setText("Nombre");

        labelCantidadProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCantidadProducto1.setText("Cantidad");

        labelPrecioProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPrecioProducto1.setText("Precio");

        labelCategoriaProducto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCategoriaProducto1.setText("Categoría");

        cmbActualizarCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cmbActualizarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aseo", "Víveres" }));

        txtActualizarPrecioProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtActualizarPrecioProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtActualizarCantidadProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtActualizarCantidadProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtActualizarNombreProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtActualizarNombreProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnActualizarPorID1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnActualizarPorID1.setText("Actualizar por ID");
        btnActualizarPorID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPorID1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ID");

        txtIDProducto.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtIDProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnEliminarProductos.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        btnEliminarProductos.setText("Eliminar");
        btnEliminarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnActualizarPorID1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnEliminarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombreProducto1)
                            .addComponent(labelCantidadProducto1)
                            .addComponent(labelPrecioProducto1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtActualizarNombreProducto)
                                    .addComponent(txtActualizarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtActualizarCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(txtIDProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelCategoriaProducto1)
                        .addGap(97, 97, 97)
                        .addComponent(cmbActualizarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(119, 119, 119))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIDProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActualizarNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombreProducto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActualizarCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCantidadProducto1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioProducto1)
                    .addComponent(txtActualizarPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCategoriaProducto1)
                    .addComponent(cmbActualizarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizarPorID1)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEliminarProductos)
                        .addComponent(btnSalir)))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Actualizar o Eliminar", jPanel3);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supermercado El Futuro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProductoActionPerformed
        // Creación de variables
        String nombre = txtNombreProducto.getText().trim();
        int cantidad = Integer.parseInt(txtCantidadProducto.getText().trim());
        double precio = Double.parseDouble(txtPrecioProducto.getText().trim());
        String categoria = cmbCategoria.getSelectedItem().toString();

        //Volvemos a realizar la conexion a la base de datos
        try {
            try ( Connection cn2 = Conexion.conectar()) {
                PreparedStatement pst2 = cn2.prepareStatement(
                        "INSERT INTO productos VALUES (?,?,?,?,?)");

                //Seteamos los valores de los txt a la base de datos (Porque es una sentencia INSERT)
                pst2.setInt(1, 0); //Se insertara el id, y como es numerico e incrementable le enviamos un 0
                pst2.setString(2, nombre);
                pst2.setInt(3, cantidad);
                pst2.setDouble(4, precio);
                pst2.setString(5, categoria);

                pst2.executeUpdate(); //Ejecutamos los cambios (La sentencia SQL)

                cn2.close();
            }

            //Ahora procedemos a limpiar los campos de texto
            Limpiar();

            //Iluminamos los campos de texto
            txtCantidadProducto.setBackground(Color.green);
            txtNombreProducto.setBackground(Color.green);
            txtPrecioProducto.setBackground(Color.green);

            JOptionPane.showMessageDialog(null, "Registro exitoso");

        } catch (SQLException e) {
            System.err.println("Error en registrar producto " + e);
            JOptionPane.showMessageDialog(null, "¡¡Error al registrar producto!! Contacte al Administrador");
        }
    }//GEN-LAST:event_btnGuardarProductoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnActualizarPorID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPorID1ActionPerformed
        // TODO add your handling code here:
        int id_producto = Integer.parseInt(txtIDProducto.getText().trim());
        String nombre_producto = txtActualizarNombreProducto.getText().trim();
        int cantidad = Integer.parseInt(txtActualizarCantidadProducto.getText().trim());
        double precio = Double.parseDouble(txtActualizarPrecioProducto.getText().trim());
        String categoria = cmbActualizarCategoria.getSelectedItem().toString();

        try {
            try ( Connection cn = Conexion.conectar()) {
                PreparedStatement pst = cn.prepareStatement(
                        "UPDATE productos SET nombre_producto = ?, cantidad_producto = ?, precio_producto = ?, categoria = ?"
                        + "WHERE id_producto = '" + id_producto + "'");

                pst.setString(1, nombre_producto);
                pst.setInt(2, cantidad);
                pst.setDouble(3, precio);
                pst.setString(4, categoria);

                pst.executeUpdate();
                cn.close();
            }

            Limpiar();

            txtActualizarCantidadProducto.setBackground(Color.green);
            txtActualizarNombreProducto.setBackground(Color.green);
            txtActualizarPrecioProducto.setBackground(Color.green);

            JOptionPane.showMessageDialog(null, "Actualización correcta");

        } catch (HeadlessException | SQLException e) {
            System.err.println("Error en actualizar producto por ID " + e);
            JOptionPane.showMessageDialog(null, "¡¡Error al actualizar producto por ID!! Contacata al Administrador");
        }
    }//GEN-LAST:event_btnActualizarPorID1ActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnEliminarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductosActionPerformed
        // TODO add your handling code here:
        int id_producto = Integer.parseInt(txtIDProducto.getText().trim());

        try {
            try ( Connection cn = Conexion.conectar()) {
                PreparedStatement pst = cn.prepareStatement(
                        "DELETE FROM productoS WHERE id_producto = '" + id_producto + "'");

                pst.executeUpdate();
                cn.close();
            }

            Limpiar();

            txtActualizarCantidadProducto.setBackground(Color.green);
            txtActualizarNombreProducto.setBackground(Color.green);
            txtActualizarPrecioProducto.setBackground(Color.green);

            JOptionPane.showMessageDialog(null, "Eliminación correcta");

        } catch (HeadlessException | SQLException e) {
            System.err.println("Error en eliminar producto por ID " + e);
            JOptionPane.showMessageDialog(null, "¡¡Error al eliminar producto!! Contacata al Administrador");
        }
    }//GEN-LAST:event_btnEliminarProductosActionPerformed

    private void btnActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablaActionPerformed
        // TODO add your handling code here:
        try {
            model.setColumnCount(0);
            model.setRowCount(0);

            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "SELECT id_producto, nombre_producto, cantidad_producto, precio_producto, categoria FROM productos");

            ResultSet rs = pst.executeQuery();

            tabla_productos = new JTable(model);
            jScrollPane1.setViewportView(tabla_productos);

            //Columnas de la tabla
            model.addColumn("ID");
            model.addColumn("Nombre");
            model.addColumn("Cantidad");
            model.addColumn("Precio");
            model.addColumn("Categoría");

            //Llenado de la tabla
            while (rs.next()) {
                Object[] fila = new Object[5];

                for (int i = 0; i < 5; i++) {
                    fila[i] = rs.getObject(i + 1);
                }

                model.addRow(fila);
            }
            cn.close();

        } catch (SQLException e) {
            System.err.println("Error en el llenado de la tabla clientes " + e);
        }

    }//GEN-LAST:event_btnActualizarTablaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPorID1;
    private javax.swing.JButton btnActualizarTabla;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton btnGuardarProducto;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbActualizarCategoria;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCantidadProducto;
    private javax.swing.JLabel labelCantidadProducto1;
    private javax.swing.JLabel labelCategoriaProducto;
    private javax.swing.JLabel labelCategoriaProducto1;
    private javax.swing.JLabel labelNombreProducto;
    private javax.swing.JLabel labelNombreProducto1;
    private javax.swing.JLabel labelPrecioProducto;
    private javax.swing.JLabel labelPrecioProducto1;
    private javax.swing.JPanel panelRegistrarProductos;
    private javax.swing.JTable tabla_productos;
    private javax.swing.JTextField txtActualizarCantidadProducto;
    private javax.swing.JTextField txtActualizarNombreProducto;
    private javax.swing.JTextField txtActualizarPrecioProducto;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtIDProducto;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables

    //Metodo para limpiar los txt
    public void Limpiar() {
        txtCantidadProducto.setText("");
        txtNombreProducto.setText("");
        txtPrecioProducto.setText("");;
        cmbCategoria.setSelectedIndex(0);
    }

}
